CREATE OR ALTER PROCEDURE sp_AltaChoferSegura
	@DNI VARCHAR(7),
	@Nombre VARCHAR(50)

AS
BEGIN
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
	BEGIN TRY
		BEGIN TRANSACTION ;
		IF EXISTS (SELECT 1 FROM DimChofer WHERE dni = @DNI)
		BEGIN 
			;THROW 51000, 'EL CHOFER YA EXISTE',1
		END

		INSERT INTO DimChofer (nombre,dni)
		VALUES (@Nombre, @DNI)

		COMMIT TRANSACTION
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
		BEGIN
			ROLLBACK TRANSACION ;
		END
		;THROW
	END CATCH
END
